### PR TITLE
helper functions for header styles

### PR DESCRIPTION
**Pull request by ryanshoover**
Adds a mixin to help with getting a background image to bleed into the header

### CODE REVIEW

**Comment by zrothauser** [comment]
@ryanshoover We just discussed moving this to BB-mods

**Comment by schrapel** [comment]
Not involved in the discussion but I am using this outside of BB so not sure if it belongs exclusively there.

**Comment by ryanshoover** [comment]
@schrapel The full conversation:

- Move the helpers into the theme mixins
- Have BB Mods use the CSS straight up instead of including the mixin

@zrothauser We were concerned about keeping unibody a "reset" repo. What if we add in a special file set for phoenix-only sass that we need across plugins & themes? I've got [these variables](https://github.com/wpengine/unibody/blob/master/assets/stylesheets/_variables.scss#L140-L142) in unibody because I need them in both the theme and in bb-mods

**Comment by ryanshoover** [comment]
Closing this PR and modifying [mar-project-phoenix#32](https://github.com/wpengine/mar-project-phoenix/pull/32) to include this mixin in the theme instead

**Pull request closed without merging**
